version: '2.1'

# mostly extending from main .yml
services:
  www:
    environment:
    - DESECSTACK_API_DEV=1
    - DESECSTACK_API_PROD=0
    depends_on:
    - webapp
    networks:
    - rearwebapp
    volumes:
    - ./www/99-desec.webapp.dev.location:/etc/nginx/sites-available/99-desec.webapp.dev.location
    logging:
      driver: "json-file"

  static:
    logging:
      driver: "json-file"

  dbapi:
    logging:
      driver: "json-file"

  dblord:
    logging:
      driver: "json-file"

  dbmaster:
    logging:
      driver: "json-file"

  api:
    environment:
    - DESECSTACK_API_DEBUG=True
    logging:
      driver: "json-file"

  nslord:
    ports:
     - "5311:53"
     - "5311:53/udp"
     - "127.0.0.1:8081:8081"
    logging:
      driver: "json-file"

  nsmaster:
    ports:
     - "5321:53"
     - "5321:53/udp"
    logging:
      driver: "json-file"

  webapp:
    image: node:latest
    volumes:
    - ./webapp/:/usr/src/app/
    working_dir: /usr/src/app/
    command: npm run dev
    environment:
    - HOST=0.0.0.0
    - PORT=443
    networks:
    - rearwebapp

networks:
  rearwebapp:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DESECSTACK_IPV4_REAR_PREFIX16}.100.0/24
        gateway: ${DESECSTACK_IPV4_REAR_PREFIX16}.100.1
