# Generated by Django 2.2.3 on 2019-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0004_domain_minimum_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='minimum_ttl',
            field=models.PositiveIntegerField(),
        ),
    ]
